### ISSUE TITLE
Error: No such image: nicolaka/netshoot:latest

### ISSUE THREAD

**Issue by themez** [aylei/kubectl-debug#134]
Hi I run into this problem using agent-less default configuration. However, I found it works if I set `verbose` to `1` Looks wired.

```
Waiting for pod debug-agent-pod-xxx to run...
Forwarding from 127.0.0.1:10027 -> 10027
Forwarding from [::1]:10027 -> 10027
Handling connection for 10027
                             Start deleting agent pod my-pod-xxx
error execute remote, Internal error occurred: error attaching to container: Error: No such image: nicolaka/netshoot:latest
error: Internal error occurred: error attaching to container: Error: No such image: nicolaka/netshoot:latest
```

**Comment by lx1036** [comment]
me too. how to resolve it?

**Comment by wanminny** [comment]
+1

**Comment by yangli8866** [comment]
+1

**Comment by yaoyaoio** [comment]
建议先docker pull nicolaka/netshoot:latest 一下看看

**Comment by hillbun** [comment]
docker pull nicolaka/netshoot:latest可以

**Comment by fforloff** [comment]
The same error for me. While pulling the image locally works, the "kubectl debug..." does not.

**Comment by lwabish** [comment]
seems that we need to ensure the images exists on the cluster nodes

**Comment by fforloff** [comment]
> seems that we need to ensure the images exists on the cluster nodes

which was not the case before

**Comment by lwabish** [comment]
> > seems that we need to ensure the images exists on the cluster nodes
> 
> which was not the case before

right, last time I didn't pre pull the netshoot image

**Comment by aylei** [comment]
Sorry for the late response, it is caused by an unstable `debug-agent` pushed to docker hub recently. It should have been fixed now, please run the command again to verify.

Since `kubectl-debug` plugin will still pull `debug-agent:latest` by default before #135 get fixed, it is recommend to configure or specify `--agent-image=aylei/debug-agent:${version}` if you are using a stable version of the plugin.

**Comment by lwabish** [comment]
> Sorry for the late response, it is caused by an unstable `debug-agent` pushed to docker hub recently. It should have been fixed now, please run the command again to verify.
> 
> Since `kubectl-debug` plugin will still pull `debug-agent:latest` by default before #135 get fixed, it is recommend to configure or specify `--agent-image=aylei/debug-agent:${version}` if you are using a stable version of the plugin.

Thanks for your work. Tried again but still not fixed. I have reinstalled the debug-agent and also tried `brew upgrade kubectl-debug`. Is there anything else I forgot?

**Comment by aylei** [comment]
> Thanks for your work. Tried again but still not fixed. I have reinstalled the debug-agent and also tried `brew upgrade kubectl-debug`. Is there anything else I forgot?

Are you encountering the same error (image not found)? And what's the image of debug agent?

**Comment by lwabish** [comment]
> > Thanks for your work. Tried again but still not fixed. I have reinstalled the debug-agent and also tried `brew upgrade kubectl-debug`. Is there anything else I forgot?
> 
> Are you encountering the same error (image not found)? And what's the image of debug agent?

Yes.The debug-agent daemonset is using `aylei/debug-agent:latest` and the `imagePullPolicy` has been set to  always.

**Comment by aylei** [comment]
@lwabish could you please try `aylei/debug-agent:v0.1.1`?

**Comment by lwabish** [comment]
> @lwabish could you please try `aylei/debug-agent:v0.1.1`?

Just tried using `kubectl debug ${POD_NAME} --agent-image=aylei/debug-agent:v0.1.1`,worked as expected

**Comment by alexdoka** [comment]
@lwabish it doesn't work for me

**Comment by lwabish** [comment]
> @lwabish it doesn't work for me

append --agentless=true

**Comment by moluzhui** [comment]
> Hi I run into this problem using agent-less default configuration. However, I found it works if I set `verbose` to `1` Looks wired.
> 
> ```
> Waiting for pod debug-agent-pod-xxx to run...
> Forwarding from 127.0.0.1:10027 -> 10027
> Forwarding from [::1]:10027 -> 10027
> Handling connection for 10027
>                              Start deleting agent pod my-pod-xxx
> error execute remote, Internal error occurred: error attaching to container: Error: No such image: nicolaka/netshoot:latest
> error: Internal error occurred: error attaching to container: Error: No such image: nicolaka/netshoot:latest
> ```

@aylei @themez   The problem seems to be caused [here](https://github.com/aylei/kubectl-debug/blob/33caedd99cd440dccd7800e10b04cad6293b2dfa/pkg/agent/runtime.go#L131), I delete the verbosity comparison in this part, and then I can download the image
```
// pkg/agent/runtime.go
	// delete if statement
        if cfg.verbosity > 0 {
		term.DisplayJSONMessagesStream(out, cfg.stdout, 1, true, nil)
	}
```
I understand that I went to the follow-up process(creat container) `before the image pull was completed`, so it caused an error 

But the docker client uses `http`, which seems to return `resp.body directly`, there is no delay waiting problem.
```
	out, err := c.client.ImagePull(ctx, image, types.ImagePullOptions{RegistryAuth: authStr})
```

Looking forward to solving the confuse.

> make build by **master** branch
